### ISSUE TITLE
error when replacing hairpin sequence

### ISSUE THREAD

**Issue by jyesselm** [YesselmanLab/rna_library#1]
Sequence = 'GGAACAGCACUUCGGUGCAAACAGUCGUAGCGAGUAGCUACGGCUGAAAGUGAUCCGUAUAUGGCGCGUGCUCCCCAUGACUUGAAGGAAACUUCAAGUGCUCCCGUGGACGUGCCUAAGUAUGGAUCACACAAAGAAACAACAACAACAAC'
Structure = '......((((....))))...((((((((((.....))))))))))...(((((((((((..(((((((.....(((((((((((((....)))))))).....))))))))))))...)))))))))))......................'

```
SS = rl.SecStruct(row["structure"], row["sequence"])
ids = SS.get_ids("Hairpin")
for i, name, seq in ids:
    if seq != 'GGAAAC':
        continue
    SS.change_motif(i, "(....)", "CUUCGG", True)
```

Returns 

`setup.py 124 gen_uucg_set
SS.change_motif(i, "(....)", "CUUCGG", True)

secstruct.py 205 change_motif
self.motif_replace_(m_id, new_secstruct, new_sequence)

secstruct.py 116 motif_replace_
for child in motif.parent().children():`

**Comment by chrisjurich** [comment]
Resolved with commit: https://github.com/YesselmanLab/rna_library/commit/540c4f26d73df9f1c1bf8cb31716e57d9878583d

try the below code to test

```
import rna_library as rl
seq = 'GGAACAGCACUUCGGUGCAAACAGUCGUAGCGAGUAGCUACGGCUGAAAGUGAUCCGUAUAUGGCGCGUGCUCCCCAUGACUUGAAGGAAACUUCAAGUGCUCCCGUGGACGUGCCUAAGUAUGGAUCACACAAAGAAACAACAACAACAAC'
ss =  '......((((....))))...((((((((((.....))))))))))...(((((((((((..(((((((.....(((((((((((((....)))))))).....))))))))))))...)))))))))))......................'

SS = rl.SecStruct(ss, seq)

print(SS.structure)
print(SS.sequence)
ids = SS.get_ids("Hairpin")
for i, name, seq in ids:
    if seq != 'GGAAAC':
        continue
    SS.change_motif(i, "(....)", "CUUCGG", True)


print(SS.structure)
print(SS.sequence)
```
